Samples -> Gram stain (+/-)
Gram stain (+/-) -> Gram negative
Gram stain (+/-) -> Gram positive
Gram positive -> G+ Cocci
Gram positive -> G+ Rods
Gram negative -> G- Cocci
Gram negative -> G- Rods

G+ Cocci -> Cocci Catalase Test
Cocci Catalase Test -> Positive (CC)
Cocci Catalase Test -> Negative (CC)
Positive (CC) -> Coagulase test (CC)
# #micol 14-16
Coagulase test (CC) -> Positive (Coagulase)
Coagulase test (CC) -> Negative (Coagulase)
Positive (Coagulase) -> Mannitol Salt Agar (MSA)
Mannitol Salt Agar (MSA) -> Growth in MSA
Growth in MSA -> Staphylococcus aureus: finalized species
Staphylococcus aureus.shape: diamond
Negative (Coagulase) -> Novobiocin sensitivity test
Novobiocin sensitivity test -> Novobiocin sensitive
Novobiocin sensitivity test -> Novobiocin resistant
Novobiocin sensitive -> Staphylococcus epidermidis: finalized species
Staphylococcus epidermidis.shape: diamond
Novobiocin resistant -> Staphylococcus saprophyticus: finalized species
Staphylococcus saprophyticus.shape: diamond
Negative (CC) -> Horse Blood Agar (HBA)
Horse Blood Agar (HBA) -> HBA alpha-hemolytic
Horse Blood Agar (HBA) -> HBA beta-hemolytic
Horse Blood Agar (HBA) -> HBA gamma non-hemolytic
HBA alpha-hemolytic -> Optochin sensitivity test
Optochin sensitivity test -> Optochin sensitive
Optochin sensitivity test -> Optochin resistant
Optochin sensitive -> Streptococcus pneumoniae: finalized species
Streptococcus pneumoniae.shape: diamond
Optochin resistant -> Streptococcus mitis: finalized species
Streptococcus mitis.shape: diamond

G+ Rods -> Endospore formation
Endospore formation -> Negative (REf)
Endospore formation -> Positive (REf)
Positive (REf) -> Rod Catalase Test
Negative (REf) -> Listeria monocytogenes: finalized species
Listeria monocytogenes.shape: diamond

Rod Catalase Test -> Positive (RC)
Rod Catalase Test -> Negative (RC)
Positive (RC) -> Coagulase test (RCg)
Negative (RC) -> Clostridium spp

Coagulase test (RCg) -> Negative (RCg)
Coagulase test (RCg) -> Positive (RCg)
Negative (RCg) -> Corynebacterium spp: finalized species
Corynebacterium spp.shape: diamond

ENDOSPORE FORMATION FOR ROD + for catalase
