Samples -> Gram stain (+/-)
Gram stain (+/-) -> Gram negative
Gram stain (+/-) -> Gram positive
Gram positive -> G+ Cocci
Gram positive -> G+ Rods
Gram negative -> G- Cocci
Gram negative -> G- Rods

G+ Cocci -> Cocci Catalase Test
Cocci Catalase Test -> Positive (CC)
Cocci Catalase Test -> Negative (CC)
Positive (CC) -> Coagulase test (CC)

G+ Rods -> Endospore formation
Endospore formation -> Negative (REf)
Endospore formation -> Positive (REf)
Positive (REf) -> Rod Catalase Test
Negative (REf) -> Listeria monocytogenes: finalized species
Listeria monocytogenes.shape: diamond

Rod Catalase Test -> Positive (RC)
Rod Catalase Test -> Negative (RC)
Positive (RC) -> Motility test (wet mount)
Motility test (wet mount) -> Motile (RMt) -> Mannitol-Egg-Yolk-Polymyxin (MYP) agar
Mannitol-Egg-Yolk-Polymyxin (MYP) agar -> Pink colonies
Pink colonies -> Bacillus cereus: finalized species
Mannitol-Egg-Yolk-Polymyxin (MYP) agar -> Yellow colonies
Yellow colonies -> Bacillus subtilis: finalized species

Bacillus cereus.shape: diamond
Bacillus subtilis.shape: diamond

Motility test (wet mount) -> Non-motile (RMt)
Non-motile (RMt) -> Corynebacterium spp: finalized species

Corynebacterium spp.shape: diamond
Corynebacterium spp: {tooltip: These can potentially be more easily identified by their club-shape, but we aren't experienced microbiologists, hence the caution}


Negative (RC) -> Clostridium spp: finalized species
Clostridium spp.shape: diamond





