Checklist: {

Tests: |md
 # Used biochemical tests
- Oxidase test
- Catalase test
- Coagulase test   
- XXXXXXX  Urease test
- XXXXXXX Capsule stain
- XXXXXXX Germ tube test
- Antibiotic discs (Bacitracin, optochin, STILL NEED novobiocin)
- XXXXXXX Microbact strips 12A/12E
- Gram-stain
- Endospore stain
- CAMP test
- XXXXXXX Indole test

 # Used agar plates
- XXXXXXX Nutrient agar
- Horse blood agar
- XXXXXXX MacConkey agar
- Bile esculin agar
- Mannitol salt agar
- XXXXXXX EMB agar
- MYP agar
- XXXXXXX Simmons’ Citrate agar
- XXXXXXX XLD agar
- XXXXXXX DNase agar
- XXXXXXX Chocolate agar
- XXXXXXX Sabouraud dextrose agar
- XXXXXXX Pseudomonas Chromagar
- Candida Chromagar
And further comments
|
}


Samples -> Gram stain (+/-)
Gram stain (+/-) -> Gram negative
Gram stain (+/-) -> Gram positive
Gram stain (+/-) -> Indefinite (perhaps no bacteria seen, or purple spots)
Indefinite (perhaps no bacteria seen, or purple spots): {tooltip: as shown by https://thunderhouse4-yuri.blogspot.com/2010/09/mycobacterium-tuberculosis-in-gram.html - according to DOI: 10.3412/jsb.46.533. M.tb can sometimes be stained as Gram-positive, whereas M. leprae is unstainable (by Gram staining), this can change if heating of the bacteria is done before the procedure}

Indefinite (perhaps no bacteria seen, or purple spots) -> Ziehl-Neelsen stain -> Less intense red-stain colour
Ziehl-Neelsen stain -> More intense red-stain colour 
Less intense red-stain colour -> Mycobacterium leprae: finalized species
More intense red-stain colour -> Mycobacterium tuberculosis:finalized species
Less intense red-stain colour: {tooltip: M. leprae is less acid fast than other microbacteria (https://www.sciencedirect.com/science/article/abs/pii/B978141604044650114X) leading to lower penetration of carbol-fuchsin}
Ziehl-Neelsen stain -> Attempt growth Lowenstein-Jensen or Middlebrook 7H10/7H11 agar
Attempt growth Lowenstein-Jensen or Middlebrook 7H10/7H11 agar -> No growth on LJ/Middlebrook -> Mycobacterium leprae
Attempt growth Lowenstein-Jensen or Middlebrook 7H10/7H11 agar: {tooltip: M. leprae is famously incultivatible in artificial media, with success found only in humans, footpads of mice, and armadillos, PCR would be nice to use for this}

Attempt growth Lowenstein-Jensen or Middlebrook 7H10/7H11 agar -> Brown granular colonies (Mtb) -> Mycobacterium tuberculosis
Brown granular colonies (Mtb): {tooltip: this will take four weeks so not really viable}


Mycobacterium leprae.shape: diamond
Mycobacterium tuberculosis.shape: diamond
Mycobacterium Leprae or Mycobacterium Tuberculosis.

Gram positive -> G+ cocci
Gram positive -> Budding yeasts
Gram positive -> G+ rods
Gram negative -> G- cocci
Gram negative -> G- rods

Budding yeasts -> Candida Chromagar 
Candida Chromagar -> Green colonies
 Green colonies -> Candida albicans: finalized species
Candida albicans.shape: diamond

Candida Chromagar -> Mauve colonies 
Mauve colonies -> Candida glabrata: finalized species
Candida glabrata.shape: diamond

G+ cocci -> Cocci catalase test
Cocci catalase test -> Positive (CC)
Cocci catalase test -> Negative (CC)
Positive (CC) -> Coagulase test (CC)

# micol 14-16
Coagulase test (CC) -> Positive (Coagulase)
Coagulase test (CC) -> Negative (Coagulase)
Positive (Coagulase) -> Mannitol Salt Agar (MSA)
Mannitol Salt Agar (MSA) -> Growth in MSA
Growth in MSA -> Staphylococcus aureus: finalized species
Staphylococcus aureus.shape: diamond
Negative (Coagulase) -> Novobiocin sensitivity test
Novobiocin sensitivity test -> Novobiocin sensitive
Novobiocin sensitivity test -> Novobiocin resistant
Novobiocin sensitive -> Staphylococcus epidermidis: finalized species
Staphylococcus epidermidis.shape: diamond
Novobiocin resistant -> Staphylococcus saprophyticus: finalized species
Staphylococcus saprophyticus.shape: diamond

Negative (CC) -> Bile esculin agar (CC)

Bile esculin agar (CC): {tooltip: Only group D streptoccocus and enterococci can hydrolyze esculin, sourced from https://www.sciencedirect.com/science/article/abs/pii/B9780750601870500079 and confirmation via "https://microbenotes.com/streptococcus-mitis}

Bile esculin agar (CC) -> Growth and esculin hydrolysis (BEcc)
Bile esculin agar (CC) -> No esculin hydrolysis (no blackening) (BEcc)
Growth and esculin hydrolysis (BEcc) -> Mannitol Salt Agar (MSA) (CC)
No esculin hydrolysis (no blackening) (BEcc) -> Horse Blood Agar (HBAcc)
Horse Blood Agar (HBAcc) -> HBA alpha-hemolytic
Horse Blood Agar (HBAcc) -> HBA beta-hemolytic
HBA beta-hemolytic -> Bacitracin sensitivity
Bacitracin sensitivity -> Sensitive to bacitracin
Bacitracin sensitivity -> Resistant to bacitracin
Resistant to bacitracin -> CAMP test (bt) -> Arrowhead of enhanced hemolysis at junction 
CAMP test (bt) -> No enhanced hemolysis 
No enhanced hemolysis -> Group C Streptococcus: finalized species
Arrowhead of enhanced hemolysis at junction -> Group B Streptococcus: finalized species
Group B Streptococcus.shape: diamond
Group C Streptococcus.shape: diamond

CAMP test (bt):{ tooltip: The CAMP test is a specific test for differentiating GBS from GCS. It involves streaking Streptococcus agalactiae perpendicularly to a streak of Staphylococcus aureus on sheep blood agar. A positive result is indicated by an arrowhead-shaped zone of enhanced hemolysis at the junction of the two streaks, caused by the synergistic action of the CAMP factor produced by GBS and the beta-hemolysin produced by S. aureus.
}

#The CAMP test is a specific test for differentiating GBS from GCS. It involves streaking #Streptococcus agalactiae perpendicularly to a streak of Staphylococcus aureus on sheep blood agar. A #positive result is indicated by an arrowhead-shaped zone of enhanced hemolysis at the junction of #the two streaks, caused by the synergistic action of the CAMP factor produced by GBS and the beta-#hemolysin produced by S. aureus.

Sensitive to bacitracin -> Streptococcus pyogenes: finalized species
Streptococcus pyogenes: {tooltip: confirm with Streptococcus grouping test}
Streptococcus pyogenes.shape: diamond

Mannitol Salt Agar (MSA) (CC) -> No growth + no colour change (MSAcc)
No growth + no colour change (MSAcc) -> Enterococcus faecium: finalized shape
Enterococcus faecium.shape: diamond

Mannitol Salt Agar (MSA) (CC): {tooltip: E. faecalis can grow on mannitol salt agar and ferment mannitol, while E. faecium lacks these phenotypes. Sourced from https://link.springer.com/article/10.1007/s11515-012-1183-5}

Mannitol Salt Agar (MSA) (CC) -> Yellow + growth (MSAcc)
Yellow + growth (MSAcc) -> Enterococcus faecalis: finalized species
Enterococcus faecalis.shape: diamond

HBA alpha-hemolytic -> Optochin sensitivity test
Optochin sensitivity test -> Optochin sensitive
Optochin sensitivity test -> Optochin resistant
Optochin sensitive -> Streptococcus pneumoniae: finalized species
Streptococcus pneumoniae.shape: diamond
Optochin resistant -> Streptococcus mitis: finalized species
Streptococcus mitis.shape: diamond

G+ rods -> Endospore formation
Endospore formation -> Negative (REf)

Negative (REf) -> Motility test (wet mount)
Motility test (wet mount) -> Non-motile (RMt)
Motility test (wet mount) -> Motile (RMt) 

Non-motile (RMt) -> Corynebacterium spp: finalized species
Motile (RMt) -> Listeria monocytogenes: finalized species

Endospore formation -> Positive (REf)
Positive (REf) -> Rod catalase test

Negative (REf) -> Corynebacterium
Listeria monocytogenes.shape: diamond

Rod catalase test -> Positive (RC)
Rod catalase test -> Negative (RC)


Positive (RC) -> Mannitol-Egg-Yolk-Polymyxin (MYP) agar
Mannitol-Egg-Yolk-Polymyxin (MYP) agar -> Pink colonies
Pink colonies -> Bacillus cereus: finalized species
Mannitol-Egg-Yolk-Polymyxin (MYP) agar -> Yellow colonies
Yellow colonies -> Bacillus subtilis: finalized species

Bacillus cereus.shape: diamond
Bacillus subtilis.shape: diamond



Corynebacterium spp: {tooltip: These can potentially be more easily identified by their club-shape, but we aren't experienced microbiologists, hence the caution}
Corynebacterium spp.shape: diamond

Negative (RC) -> Clostridium spp: finalized species
Clostridium spp.shape: diamond
